apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/azure/storage/10086-icon-service-Storage-Accounts.svg
  alias: {{ match_resource.resource_group.name }} Azure Storage Health
  asMeasuredBy: Composite health score of resources & activities. 
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: Azure Storage Health should be maintained by ensuring there are no unused disks, snapshots, or storage accounts, and that storage accounts have appropriate public access restrictions.
  additionalContext:  
    {% include "azure-hierarchy.yaml" ignore missing %}
    qualified_name: "{{ match_resource.qualified_name }}"
  tags:
    {% include "azure-tags.yaml" ignore missing %}
    - name: service
      value: storageaccount
    - name: access
      value: read-only