apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://placeholder.svg
  alias: Azure Storage Health in resource group {{ match_resource.resource_group.name }} in azure subscription {{ custom.subscription_name }}
  asMeasuredBy: Composite health score of resources & activities. 
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: Azure Storage Health should be maintained by ensuring there are no unused disks, snapshots, or storage accounts, and that storage accounts have appropriate public access restrictions.
  additionalContext:
    name: "{{match_resource.resource.name}}"
    tags: "{{match_resource.tags}}"
    qualified_name: "{{ match_resource.qualified_name }}"
    resource_group: "{{ match_resource.resource_group.name }}"
    subscription_id: "{{ match_resource.subscription_id }}"