apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/azure/databases/10135-icon-service-Managed-Database.svg
  alias:  {{ match_resource.resource_group.name }} Azure Database Health
  asMeasuredBy: Composite health score of resources & activities. 
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The health of Azure databases is measured by evaluating multiple factors like public accessibility, replication status, high availability configuration, CPU utilization, memory usage, and cache performance.
  additionalContext:  
    {% include "azure-hierarchy.yaml" ignore missing %}
    qualified_name: "{{ match_resource.qualified_name }}"
  tags:
    {% include "azure-tags.yaml" ignore missing %}
    - name: service
      value: database
    - name: access
      value: read-only